---
- name: Update package lists on Ubuntu
  hosts: all
  become: yes
  vars:
    ansible_become_password: "Zahra786!"
  tasks:
    - name: Run sudo apt update
      ansible.builtin.shell: "sudo apt update"
      register: update_output

    - name: Display apt update output
      ansible.builtin.debug:
        var: update_output.stdout_lines
